version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: postgres2024
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./packages/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://userdb:postgres2024@postgres:5432/postgresdb
    command: sh -c "npx prisma migrate deploy && npm start"

  url-service:
    build: ./packages/url-shortener-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://userdb:postgres2024@postgres:5432/postgresdb
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres-data: