openapi: 3.0.0
info:
  title: Auth Service API
  description: API para autenticação de usuários
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /auth/register:
    post:
      summary: Registro de novo usuário
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "201":
          description: Usuário registrado com sucesso
        "400":
          description: Dados inválidos

  /auth/login:
    post:
      summary: Login de usuário
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          description: Parametros inválidos
        "401":
          description: Credenciais inválidas
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
