name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgresdb
          POSTGRES_USER: userdb
          POSTGRES_PASSWORD: postgres2024
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Install dependencies for auth-service
        run: npm install
        working-directory: ./packages/auth-service

      - name: Run prisma migrations
        run: npx prisma migrate deploy
        working-directory: ./packages/auth-service

      - name: Run tests for auth-service
        run: npm run test
        working-directory: ./packages/auth-service

      - name: Install dependencies for url-shortener-service
        run: npm install
        working-directory: ./packages/url-shortener-service

      - name: Run tests for url-shortener-service
        run: npm run test
        working-directory: ./packages/url-shortener-service
